# Site settings
title: VingoH'blog
SEOTitle: VingoH的博客
header-img: img/system/header-shouye.jpg
email:
description: "VingoH'blog."
keyword: "Yifan Huo, VingoH的博客"
url: "http://vingoh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/vingoh/vingoh.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Chaos is a ladder."
sidebar-avatar: /img/system/about-myself.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
# zhihu_username:     
github_username:    vingoh
#facebook_username:
#jianshu_username:  
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  math_engine: mathjax                  # LaTeX math blocks for MathJax in browser


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Ov23liuunBYCBv5rNFSQ  #生成的clientID
  clientSecret: 9a03a482f1917c574f5622d48fbdf1962a7c0707   #生成的clientSecret
  repo: vingoh.github.io    #仓库名称
  owner: vingoh    #github用户名
  admin: vingoh
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 5c6b7299917164e5e5b79e7b3b3e6dd2

# Google Analytics
ga_track_id: 'G-FB4GGPKKE6'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



